INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1001', 'Andhik Ampuh Yunanto', 'andhik@mail.com', 'andhik', null, null, null, 2);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1002', 'Mike Yuliana', 'mike@mail.com', 'mike', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1003', 'Mohammad Zikky', 'zikky@mail.com', 'zikky', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1004', 'Mohamad Nasyir Tamara', 'nasyir@mail.com', 'nasyir', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1005', 'Farid Dwi Murdianto', 'farid@mail.com', 'farid', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1006', 'Maretha Ruswiansari', 'maretha@mail.com', 'maretha', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1007', 'Hero Yudo Martono', 'hero@mail.com', 'hero', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1008', 'Fadilah Fahrul Hardiansyah', 'fadilah@mail.com', 'fadilah', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1009', 'Iwan Syarif', 'iwan@mail.com', 'iwan', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1010', 'Bima Sena Bayu Dewantara', 'bima@mail.com', 'bima', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1011', 'Ida Anisah', 'ida@mail.com', 'ida', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1012', 'Reesa Akbar', 'reesa@mail.com', 'reesa', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1013', 'Joke Pratilastiarso', 'joke@mail.com', 'joke', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1014', 'Fardani Annisa Damastuti', 'fardani@mail.com', 'fardani', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1015', 'Muhammad Agus Zainuddin', 'agus@mail.com', 'agus', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1016', 'Arna Fariza', 'arna@mail.com', 'arna', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1017', 'Desy Intan Permatasari', 'desy@mail.com', 'desy', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1018', 'Entin Martiana', 'entin@mail.com', 'entin', null, null, null, 1);
INSERT INTO pegawai(nip, nama_lengkap, email, password, remember_token, created_at, updated_at, role_id) VALUES ('1019', 'admin', 'admin@admin.com', 'admin', null, null, null, 2);
